name: Build and Deploy

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install
        
      # - name: Run Tests
      #   run: npm test

      - name: Compile
        run: npm run build

      - name: Create Artifact
        run: tar -czvf dist.tar.gz dist

      - name: Add artifact to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist.tar.gz
      
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: dist.tar.gz

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: output

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Rename file
        run: mv dist.tar.gz ${{ github.sha }}.tar.gz

      - name: Copy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "${{ github.sha }}.tar.gz"
          target: "builds"

      - name: Add SSH key to known_hosts
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Execute Deployment Script
        run: ./dev-bin/deploy.sh ${{ !github.event.release.prerelease }} ${{ github.sha }}
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        